CREATE TABLE `live_telemetry` (
	`rider_id` INT(10) UNSIGNED NOT NULL,
	`msec` BIGINT(20) UNSIGNED NOT NULL,
	`power` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`speed` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`hr` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`cad` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`duration` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
	`meters` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
	`elevation` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`mwh` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
	`fwd` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`heading` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`lean_angle` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`x` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`y` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`z` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`grp` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`ride_ons` SMALLINT(5) UNSIGNED NOT NULL,
	PRIMARY KEY (`rider_id`),
	INDEX `msec` (`msec`),
	INDEX `grp` (`grp`)
)
COLLATE='utf8mb4_general_ci'
ENGINE=MEMORY
;
